data:extend(
{
  {
    type = "virtual-signal",
    name = "signal-es-tr-coal",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-coal.png",
    subgroup = "evs-tr-raw",
    order = "e",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-copper-ore",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-copper-ore.png",
    subgroup = "evs-tr-raw",
    order = "e",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-iron-ore",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-iron-ore.png",
    subgroup = "evs-tr-raw",
    order = "e",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-raw-wood",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-raw-wood.png",
    subgroup = "evs-tr-raw",
    order = "e",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-stone",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-stone.png",
    subgroup = "evs-tr-raw",
    order = "e",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-rare-earth-ore",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-rare-earth-ore.png",
    subgroup = "evs-tr-raw",
    order = "e",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-crude-oil",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-crude-oil.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-heavy-oil",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-heavy-oil.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-light-oil",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-light-oil.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-lubricant",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-lubricant.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-petroleum-gas",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-petroleum-gas.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-sulfuric-acid",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-sulfuric-acid.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-water",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-water.png",
    subgroup = "evs-tr-liquid",
    order = "f",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-advanced-circuit",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-advanced-circuit.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-alien-artifact",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-alien-artifact.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-battery",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-battery.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {  
    type = "virtual-signal",
    name = "signal-es-tr-copper-plate",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-copper-plate.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-electronic-circuit",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-electronic-circuit.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-iron-plate",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-iron-plate.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-plastic-bar",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-plastic-bar.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-processing-unit",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-processing-unit.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-solid-fuel",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-solid-fuel.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-steel-plate",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-steel-plate.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-stone-brick",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-stone-brick.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
  {
    type = "virtual-signal",
    name = "signal-es-tr-sulfur",
    icon = "__Extra-Virtual-Signals__/graphics/tr/evs-tr-sulfur.png",
    subgroup = "evs-tr-intermedite",
    order = "g",
  },
}
)