data:extend(
{
  {
    type = "virtual-signal",
    name = "signal-es-ls-coal",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-coal.png",
    subgroup = "evs-ls-raw",
    order = "b",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-copper-ore",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-copper-ore.png",
    subgroup = "evs-ls-raw",
    order = "b",
  },
 {
    type = "virtual-signal",
    name = "signal-es-ls-iron-ore",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-iron-ore.png",
    subgroup = "evs-ls-raw",
    order = "b",
  }, 
  {
    type = "virtual-signal",
    name = "signal-es-ls-raw-wood",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-raw-wood.png",
    subgroup = "evs-ls-raw",
    order = "b",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-stone",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-stone.png",
    subgroup = "evs-ls-raw",
    order = "b",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-rare-earth-ore",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-rare-earth-ore.png",
    subgroup = "evs-ls-raw",
    order = "b",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-crude-oil",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-crude-oil.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  }, 
  {
    type = "virtual-signal",
    name = "signal-es-ls-heavy-oil",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-heavy-oil.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-light-oil",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-light-oil.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-lubricant",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-lubricant.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-petroleum-gas",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-petroleum-gas.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-sulfuric-acid",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-sulfuric-acid.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-water",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-water.png",
    subgroup = "evs-ls-liquid",
    order = "c",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-advanced-circuit",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-advanced-circuit.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-alien-artifact",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-alien-artifact.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-battery",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-battery.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-copper-plate",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-copper-plate.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-electronic-circuit",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-electronic-circuit.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-iron-plate",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-iron-plate.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-plastic-bar",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-plastic-bar.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-processing-unit",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-processing-unit.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-solid-fuel",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-solid-fuel.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-steel-plate",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-steel-plate.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-stone-brick",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-stone-brick.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
  {
    type = "virtual-signal",
    name = "signal-es-ls-sulfur",
    icon = "__Extra-Virtual-Signals__/graphics/ls/evs-ls-sulfur.png",
    subgroup = "evs-ls-intermedite",
    order = "d",
  },
}
)
